apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.levi.com
spec:
  scope: Namespaced
  names:
    kind: Bucket
    plural: buckets
    shortNames:
    - bk
  group: levi.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                bucketName:
                  type: string
                region:
                  type: string